#!/bin/bash

#should I do this on startvnc?
vglclient &

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

#fslview can only handle 1 image?
vglrun trackvis `find /input -name *.trk` &

#find the window id
pid=$!
#sleep 2
#id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
##echo $id > /id.txt
#wmctrl -i -r $id -b add,fullscreen

#run it for an hour
sleep 3600
